TrajectoryPlannerROS:
   max_vel_x: 1
   min_vel_x: -1
   max_vel_theta: 1
   min_vel_theta: -1
   acc_lim_theta: 3.0
   acc_lim_x: 2.5
   acc_lim_y: 2.5
   min_in_place_vel_theta: 0.5
   escape_vel: -0.3

   holonomic_robot: false

   pdist_scale: 3.0
   gdist_scale: .1
   meter_scoring: true

   occdist_scale: .02
   prune_plan: false

   sim_time: 3.0
   sim_granularity: 0.005
   vx_samples: 20
   vtheta_samples: 40
   latch_xy_goal_tolerance: false



  
