map_type: costmap
footprint: [[0.21,0.21], [0.21,-0.21], [-0.21,-0.21], [-0.21,0.21]]

robot_radius: .25
obstacle_range: 1.0
raytrace_range: 1.0
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /mazebot/laser/scan, marking: true, clearing: true}

cost_scaling_factor: .1
inflation_radius: 1.0


