global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 10
   publish_frequency: 10
   width: 5
   height: 5
   resolution: 0.02
   static_map: true
   rolling_window: false


   
