local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 15
   publish_frequency: 15
   width: 4
   height: 4
   resolution: 0.02
   static_map: false
   rolling_window: true

 
