TrajectoryPlannerROS:

  max_vel_x: 5.0
  min_vel_x: -5.0
  max_vel_theta: 5.0
  min_vel_theta: -5.0
  min_in_place_vel_theta: 0.5

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  sim_time: 10.0
  meter_scoring: true
  pdist_scale: 1.5
  gdist_scale: 0.5
  occdist_scale: 0.01
    
  holonomic_robot: false

  
